version: "3.9"

services:
  postgres:
    environment:
      POSTGRES_DB: uno_test

  redis:
    command: redis-server

  server:
    environment:
      ENV: test
      DATABASE_URL: postgres://uno:uno_dev@postgres:5432/uno_test?sslmode=disable
      REDIS_URL: redis://redis:6379/0
    command: go test ./...
