version: "3.9"

services:
  postgres:
    environment:
      POSTGRES_DB: wilddeck_test

  redis:
    command: redis-server

  server:
    environment:
      ENV: test
      DATABASE_URL: postgres://wilddeck:wilddeck_dev@postgres:5432/wilddeck_test?sslmode=disable
      REDIS_URL: redis://redis:6379/0
    command: go test ./...
